---
- hosts: ubuntu-quota
  tasks:
    - name: Update packages
      apt: update_cache=yes upgrade=dist
    - name: Install Quota apt Package
      apt: name=quota state=latest
#    - name: Install linux-image-extra-virtual which is required for kernel quota support
#      apt: name="linux-image-extra-virtual" state=latest
  - name: Modify mount-options for /
    mount:
      path: "/"
      src: "UUID={{ ansible_mounts | json_query('[?mount == `/`] | [0].uuid') }}"
      fstype: "ext4"
      opts: "errors=remount-ro,usrquota,grpquota"
      state: "present"